name: tests

on: push

jobs:
  Workflow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Intalling Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.
      - name: pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: run install, format and test
        run: |
          pnpm install
          pnpm lint
          pnpm test
